### ISSUE TITLE
Tablas de Verdad

### ISSUE THREAD

**Issue by 00Asaf00** [SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-club-noobbaby#1]
- [**_Tabla de verdad_**](https://drive.google.com/file/d/1ryxlh0SFHHkbEPy1Q1zRbSNFUYGo2wOn/view?usp=sharing)

**Comment by 23620031** [comment]
PORTADA 25/25
PROCEDIMIENTO 20/25 (faltó objetivo)
FIGURAS 25/25
RESULTADO Y CONCLUCIÓN 20/25 (falta resultados)
_______________________________________________________________________________
CALIFICACIÓN TOTAL 18/20

CALIFICADO POR ISAÍAS Y EQUIPO

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
